  apiVersion: v1
  kind: Service
  metadata:
#   annotations:
#     openshift.io/generated-by: OpenShiftNewApp
#   creationTimestamp: 2019-04-09T09:17:34Z
#   labels:
#     app: nodejs-ex
    name: nodejs-ex
#   namespace: youpi
#   resourceVersion: "3529582879"
#   selfLink: /api/v1/namespaces/youpi/services/nodejs-ex
#   uid: 4f688e04-5aa8-11e9-b1ce-0a69cdf75e6f
# spec:
#   clusterIP: 172.30.195.252
#   ports:
#   - name: 8080-tcp
#     port: 8080
#     protocol: TCP
#     targetPort: 8080
#   selector:
#     app: nodejs-ex
#     deploymentconfig: nodejs-ex
#   sessionAffinity: None
#   type: ClusterIP
# status:
#   loadBalancer: {}
