pipeline {
	agent {
		node {
		  label 'nodejs' 
		}
	}
    stages {
         stage('Build') {
            steps {
                script {
					println "It works!";
				}
            }
        }
    }
}