  apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nodejs-mongodb-example
    name: nodejs-mongodb-example
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: nodejs-mongodb-example
      deploymentconfig: nodejs-mongodb-example
  status:
    loadBalancer: {}
