# apiVersion: build.openshift.io/v1
# kind: Build
# metadata:
#   annotations:
#     openshift.io/build-config.name: nodejs-ex
#     openshift.io/build.number: "1"
#     openshift.io/build.pod-name: nodejs-ex-1-build
#   creationTimestamp: 2019-04-09T09:17:34Z
#   labels:
#     app: nodejs-ex
#     buildconfig: nodejs-ex
#     openshift.io/build-config.name: nodejs-ex
#     openshift.io/build.start-policy: Serial
#   name: nodejs-ex-1
#   namespace: youpi
#   ownerReferences:
#   - apiVersion: build.openshift.io/v1
#     controller: true
#     kind: BuildConfig
#     name: nodejs-ex
#     uid: 4f26b514-5aa8-11e9-b1ce-0a69cdf75e6f
#   resourceVersion: "3529585827"
#   selfLink: /apis/build.openshift.io/v1/namespaces/youpi/builds/nodejs-ex-1
#   uid: 4f2df721-5aa8-11e9-ba57-0ab8769191d3
# spec:
#   nodeSelector: null
#   output:
#     pushSecret:
#       name: builder-dockercfg-75l52
#     to:
#       kind: ImageStreamTag
#       name: nodejs-ex:latest
#   postCommit: {}
#   resources: {}
#   revision:
#     git:
#       author:
#         email: xavierdpt@gmail.com
#         name: xavierdpt@gmail.com
#       commit: a8200504cf1ef73d94737c42c7a36b2bf4b0faa9
#       committer:
#         email: xavierdpt@gmail.com
#         name: xavierdpt@gmail.com
#       message: .
#     type: Git
#   serviceAccount: builder
#   source:
#     git:
#       uri: https://github.com/xavierdpt/nodejs-ex
#     type: Git
#   strategy:
#     sourceStrategy:
#       from:
#         kind: DockerImage
#         name: docker-registry.default.svc:5000/openshift/nodejs@sha256:b155814ac48feed9667b590a73f090367cbd7f64e34aaeb4dc70bfc8a4963ace
#       pullSecret:
#         name: builder-dockercfg-75l52
#     type: Source
#   triggeredBy:
#   - imageChangeBuild:
#       fromRef:
#         kind: ImageStreamTag
#         name: nodejs:10
#         namespace: openshift
#       imageID: docker-registry.default.svc:5000/openshift/nodejs@sha256:b155814ac48feed9667b590a73f090367cbd7f64e34aaeb4dc70bfc8a4963ace
#     message: Image change
# status:
#   completionTimestamp: 2019-04-09T09:19:20Z
#   config:
#     kind: BuildConfig
#     name: nodejs-ex
#     namespace: youpi
#   duration: 106000000000
#   output:
#     to:
#       imageDigest: sha256:849bfd8d3dee4d6c39a413578c8052ae537b831d2f659c32e32506382dfd5a7a
#   outputDockerImageReference: docker-registry.default.svc:5000/youpi/nodejs-ex:latest
#   phase: Complete
#   stages:
#   - durationMilliseconds: 1056
#     name: FetchInputs
#     startTime: 2019-04-09T09:17:41Z
#     steps:
#     - durationMilliseconds: 1056
#       name: FetchGitSource
#       startTime: 2019-04-09T09:17:41Z
#   - durationMilliseconds: 1613
#     name: CommitContainer
#     startTime: 2019-04-09T09:18:09Z
#     steps:
#     - durationMilliseconds: 1613
#       name: CommitContainer
#       startTime: 2019-04-09T09:18:09Z
#   - durationMilliseconds: 20477
#     name: Assemble
#     startTime: 2019-04-09T09:17:50Z
#     steps:
#     - durationMilliseconds: 20477
#       name: AssembleBuildScripts
#       startTime: 2019-04-09T09:17:50Z
#   - durationMilliseconds: 68333
#     name: PushImage
#     startTime: 2019-04-09T09:18:10Z
#     steps:
#     - durationMilliseconds: 68333
#       name: PushImage
#       startTime: 2019-04-09T09:18:10Z
#   startTimestamp: 2019-04-09T09:17:34Z
