# apiVersion: build.openshift.io/v1
# kind: BuildConfig
# metadata:
#   annotations:
#     openshift.io/generated-by: OpenShiftNewApp
#   creationTimestamp: 2019-04-09T09:17:34Z
#   labels:
#     app: nodejs-ex
#   name: nodejs-ex
#   namespace: youpi
#   resourceVersion: "3529582849"
#   selfLink: /apis/build.openshift.io/v1/namespaces/youpi/buildconfigs/nodejs-ex
#   uid: 4f26b514-5aa8-11e9-b1ce-0a69cdf75e6f
# spec:
#   failedBuildsHistoryLimit: 5
#   nodeSelector: null
#   output:
#     to:
#       kind: ImageStreamTag
#       name: nodejs-ex:latest
#   postCommit: {}
#   resources: {}
#   runPolicy: Serial
#   source:
#     git:
#       uri: https://github.com/xavierdpt/nodejs-ex
#     type: Git
#   strategy:
#     sourceStrategy:
#       from:
#         kind: ImageStreamTag
#         name: nodejs:10
#         namespace: openshift
#     type: Source
#   successfulBuildsHistoryLimit: 5
#   triggers:
#   - github:
#       secret: CoqlERBtZuMmIh5PYvm0
#     type: GitHub
#   - generic:
#       secret: BAp3uMwxm1PdA5mYrf5u
#     type: Generic
#   - type: ConfigChange
#   - imageChange:
#       lastTriggeredImageID: docker-registry.default.svc:5000/openshift/nodejs@sha256:b155814ac48feed9667b590a73f090367cbd7f64e34aaeb4dc70bfc8a4963ace
#     type: ImageChange
# status:
#   lastVersion: 1
